### ISSUE TITLE
Цвет фона под логотипом Курсомира...

### ISSUE THREAD

**Issue by lumenvindex** [kursomir/guides#10]
Обратил внимание, что фон под логотипом Курсомира на странице https://kursomir.github.io/guides/ несколько более светлый, чем используется у меня в видео... Более того, @basavind сказал, что этот цвет взят из нового дизайна сайта Курсомира, который ещё находится в разработке. Мне же для видеозаставки был выдан слайд с логотипом, фон которого имеет цвет ed4e42.

Так какой же цвет "верный"?

**Comment by ZverArt** [comment]
Тут нужен @eekar чтобы объяснил. Официальным цветом считается ed4e42, но в некоторых случаях у нас есть отклонения от этого цвета, как например вот здесь http://kursomir.ru/about/project

По поводу того, что этот же цвет используется в новом дизайне — не уверен. Под рукой нет нового дизайна, но насколько я помню "красный" цвет там явно не используется

**Comment by eekar** [comment]
@lumenvindex, cтоит исользовать e2412b везде, кроме финального дизайна сайта, который используется в вёрстке.

**Comment by lumenvindex** [comment]
значит ли это, что для видео нужно слайд переделать и следующие видео выпускать с фоном e2412b на первом слайде?

**Comment by ZverArt** [comment]
@eekar

**Comment by eekar** [comment]
@lumenvindex если они не критично отличаются по оттенку -- то можно оставить. В идеале переделать, если есть ресурс.

**Comment by lumenvindex** [comment]
@ZverArt, если человека раз упомянули, то он уведомления из этой ветки будет уже получать, если конечно ручками не отпишется
@eekar, ну новые-то лекции сделать с другим цветом - не проблема. проблема в том, что уже опубликованные на ютубе лекции изменять не получится без потери "просмотров" и прочей полезной статистики.
благодарю за разъяснения. жаль, что никто не уведомил о том, что "основной" цвет изменился.

**Comment by eekar** [comment]
@lumenvindex я глянул в первую итерацию основного логотипа и в исходнике посмотрел цвет. По хорошему нужно нарисовать краткий гайдлайн с основными вариантами лого и цветов.

**Comment by lumenvindex** [comment]
@eekar а в short_intro_logo_tpl.psd (самый _исходный_ файл из тех, что у меня есть) у меня вообще использован ec4e42... переделаю слайд на e2412b, а то разница в оттенках всё таки довольно заметна.

**Comment by basavind** [comment]
Не закрывайте ишью пока не будет окончательно решения.

@eekar, @gomzz может мы запилим небольшой стайлгайд по дизайну, потому как я до сих пор не понял где какой цвет используется.

**Comment by eekar** [comment]
Да, я же выше написал, что нужно это сделать.

**Comment by basavind** [comment]
Мне тогда от вас нужен набросанная в чем угодно текстовка с картинками и примерами

**Comment by eekar** [comment]
сегодня постараюсь сделать. Не обещаю.

**Comment by lumenvindex** [comment]
@basavind ок, больше не буду. просто я на свой вопрос ответ получил, вот и закрыл...

**Comment by basavind** [comment]
@eekar - сделай вечером черновик из говна и палок, закинем его как первую итерацию и постепенно будем рихтовать и обновлять, не обязательно сразу готовый вариант :))

**Comment by ZverArt** [comment]
@lumenvindex "если человека раз упомянули, то он уведомления из этой ветки будет уже получать, если конечно ручками не отпишется". Упоминать человека следует по 2 причинам:
1) На гитхабе можно включить уведомления по упоминанию;
2) Чтобы из уведомления на почте можно было сразу понять, кому адресовано сообщение.

**Comment by eekar** [comment]
Пока пусть будет так. Когда получу доступ к облаку -- залью туда и дам ссылку. 
[fin-logo-3.pdf](https://github.com/kursomir/guides/files/807231/fin-logo-3.pdf)

**Comment by basavind** [comment]
А может нам хоть чуть чуть распотрошить этот файлик на исходники и сделать вот такого типа [руководство](https://kursomir.github.io/guides/editor), чтобы можно было при необходимости и `Cmd+C` `Cmd+V` сделать?

**Comment by eekar** [comment]
сам файл лежит вот тут
https://cloud.kursomir.ru/index.php/s/v16DX93Ou5OPzvO

папка со всеми файлами лежит вот тут
https://cloud.kursomir.ru/index.php/s/NYap9TT9iCMx2HZ

**Comment by basavind** [comment]
ок, только дальнейшее обсуждение переносим вот сюда: #14, а эту ветку я временно закрываю.
