### ISSUE TITLE
Добавить гайд для переводчиков

### ISSUE THREAD

**Issue by ZverArt** [kursomir/guides#15]
Пшеничная возьмётся за первую итерацию, но как для человека ни разу не работавшего с гитом — лучше, чтобы маркдаун был заготовлен.

**Comment by basavind** [comment]
Пусть черновик скинет - найдем кто в маркдаун перегонит )

**Comment by ZverArt** [comment]
@basavind да-да, уже занимается созданием черновика. Я потом его сюда загружу :)

**Comment by lumenvindex** [comment]
по поводу маркдауна - могу я попробовать перегнать

**Comment by AgDust** [comment]
+ я могу маркдаун, я наверное пока меньше всех занят

**Comment by basavind** [comment]
https://docs.google.com/document/d/1ok8JmMtTytAAjv2LGsd420Z25Jv1V4m4WU5gWXH6BUI/edit

**Comment by lumenvindex** [comment]
если раньше никто не цапнет, через пару часов сделаю assign на себя и займусь переводом в markdown

**Comment by basavind** [comment]
Достаточно в этой написать, что ты забил ^^ в Assign можно назначать только участников группы *kursomir*, но мы надеемся, что нам еще и со стороны будут люди помогать :)

> На днях была случайная коллизия с ишью, надеюсь больше не повторится

А вообще у нас же есть четкий план по оказанию помощи — https://kursomir.github.io/

**Comment by lumenvindex** [comment]
забил! :point_up:

**Comment by AgDust** [comment]
Окей, надо было мне отписаться когда делать начал. Тогда не трогаю.

**Comment by lumenvindex** [comment]
@AgDust если начал уже - делай :)

**Comment by AgDust** [comment]
Хорошо, я мигом

**Comment by AgDust** [comment]
Сделал. Но он примазался к другому моему [пулл-реквесту](https://github.com/kursomir/guides/pull/29). Ошибку понял, но в данном случае надо ли что-то мудрить или пусть так уже?

**Comment by basavind** [comment]
Завтра с компа гляну, разрулю.

**Comment by lumenvindex** [comment]
#33
