### ISSUE TITLE
Разделить общий список гайдов на главной по направлениям

### ISSUE THREAD

**Issue by basavind** [kursomir/guides#25]
Сейчас все гайды в одной каше, было бы неплохо их разделить по направлениям, например:

- GitHub / Руководства
- Разработчикам (в том числе будет включать гайд по дизайну)
- Волонтерам (будет включать гайды для переводчиков, редакторов, монтажеров и тд.)

**Comment by lumenvindex** [comment]
ждём-с хотя бы одного гайда для раздела Разработчикам :blush:

**Comment by basavind** [comment]
Соответствующий таск на гайд для оформления деплоя заведен, так что должен появиться :)
