### ISSUE TITLE
Добавить гайд по уведомлениям

### ISSUE THREAD

**Issue by basavind** [kursomir/guides#5]
Уведомлениям в гитхабе, как их прочитать, как перейти, как ответить

**Comment by lumenvindex** [comment]
имхо, нужно начать с гайда "как добавить гайд" :)

**Comment by basavind** [comment]
Это таски скорее для разработчиков, которые "в теме" :))

На самом деле чтобы добавить гайд - в корне репы делаешь файлик с именем гайда (который станет ссылкой, например **editor**.md -> kursomir.github.io/guides/**editor**)

Фигачишь его в маркдауне, сохраняешь и всё - страничка с гайдом сама соберется из твоего маркдауна.

**Comment by basavind** [comment]
@lumenvindex может этот таск возьмёшь? :)

**Comment by lumenvindex** [comment]
@basavind да тут как-то совсем не о чем писать. всё же итак очевидно :imp:

**Comment by basavind** [comment]
Этот таск висит потому что такой вопрос возник :)

**Comment by basavind** [comment]
мой косяк с референсом, не обращайте внимания 😔

**Comment by lumenvindex** [comment]
#20
