### ISSUE TITLE
Добавить гайд по ишью для гитхаба

### ISSUE THREAD

**Issue by basavind** [kursomir/guides#6]
Гайд должен содержать объяснения для людей, далеких от сферы разработки, как создавать ишью, как создавать предложения и обсуждения.

**Comment by lumenvindex** [comment]
попробую сделать

**Comment by basavind** [comment]
Стопе :) этим прямо сейчас занимается другой человек

**Comment by ZverArt** [comment]
@basavind добавь assignee тогда

**Comment by EdwinnaElbert** [comment]
Да, извините, что не отписалась сразу
