### ISSUE TITLE
Добавить гайд для разработчиков по деплою

### ISSUE THREAD

**Issue by basavind** [kursomir/guides#8]
# Что должно быть в гайде?

Информация о том, как правильно оформить файл `DEPLOY.md`, чтобы админы могли задеплоить репу, прочитав в ней файлик `DEPLOY.md`.

# Примерное содержание файла (с примерами)

> В каждом репозитории, где есть код, который необходимо деплоить, в корне создаём файл `DEPLOY.md`, в котором размещаем следующую информацию:
> 1. набор команд на разворот (типа git clone && npm install && npm run storybook
> 2. список файлов для персистентного хранения (что никогда не должно удаляться)
> 3. зависимости/внешние сервисы/программы
>
> _Если есть возможность и навыки упаковки в Dockerfile, то упаковываем_

**Comment by basavind** [comment]
@mvaleev Если будут какие-то комментарии и дополнения - пиши сюда.

**Comment by basavind** [comment]
@AgDust Пока нет материалов для переводческого гайда, можешь этот гайд запилить? собственно что в первом комменте написано - то и запилить :) После первой итерации можешь подергать @mvaleev ^^

**Comment by AgDust** [comment]
Но... я не знаю как что надо деплоить. Только в некоторых репозиториях есть информация в README, но тогда зачем отдельный файл для этого?

**Comment by basavind** [comment]
В том то и дело, что тебе не надо знать как деплоят. Люди, ответственные за репы знают как их деплоить, но  проблема в том, что в их понимании "Да это же 2 пальца об асфальт, чО там деплоить?". У людей, которые непосредственно занимаются деплоем (админы, девопсы) каждая репа и каждый проект представляет собой отдельную боль - они не обязаны знать как деплоится тот или иной фреймворк, язык и тд.

Вот поэтому, необходимо составить гайд, как необходимо оформить в каждой репе файлик `DEPLOY.md` и что в нем должно быть (пока что это очень краткая информация - из первого коммента в этой ветке). Такой файлик позволит сказать админу — "Вась, задеплой пожалуйста вот эту репу", и Вася заходит в репу, открывает файлик `DEPLOY.md` и деплоит по указанному в файле сценарию. Для админа нет необходимости разыскивать владельца репы, тратить время на то, чтобы владелец репы понял, что деплой происходит не на его компе, а на новой чистой системе и вспомнил какие зависимости надо установить, вспомнить пару попутных факапов и тд.

**Comment by AgDust** [comment]
Форкнул, добавил DEPLOY и сделал пулл-реквест для [StatisticsAPI](https://github.com/kursomir/StatisticsAPI/pull/8), [kursomir.ru](https://github.com/kursomir/kursomir.ru/pull/11) и [Authorizer](https://github.com/kursomir/Authorizer/pull/2). В остальных или нет необходимости или неясно нужен ли этот файл и деплой вообще.

**Comment by basavind** [comment]
@AgDust... а как называется вот этот вот ишью?

**Comment by AgDust** [comment]
Эмм... ишью называется "добавить гайд по деплою", что и сбило с толку. А нужен пример написания руководства по деплою. Закрываю пулл-реквесты, откатываю изменения, сейчас напишу гайд.

**Comment by basavind** [comment]
@AgDust спасибо!

@mvaleev глянь пожалуйста https://kursomir.github.io/guides/deploy, может есть какие-то еще дополнения, пожелания?

**Comment by mvaleev** [comment]
Пока дополнений нет. По мере развития проекта отредактируем если будет необходимость.
